### ISSUE TITLE
QST: Can a task depend on another task that is parametrized?

### ISSUE THREAD

**Issue by augustebaum** [pytask-dev/pytask#319] opened 2022-11-25 08:25 UTC
#### Question about pytask

[This docs article](https://pytask-dev.readthedocs.io/en/stable/tutorials/repeating_tasks_with_different_inputs.html) explains how to repeat a task for several inputs, and in [this part](https://pytask-dev.readthedocs.io/en/stable/tutorials/repeating_tasks_with_different_inputs.html#complex-example) we see how we can essentially pass arguments to tasks.

My question is, is it possible for another task to then depend on such a parametrized task? For example, if `task_create_random_data` produces `f"data_{i}.pkl"` for `i` in [0, 9], can I then create a task `task_use_random_data` that depends on `data_4.pkl`? Or even weirder, could I create a task that depends on `f"data_{i}.pkl"` for `i` in [0, 9] again?

My follow-up question is that I'd like to parametrize my tasks with a config file, so in my tests so far things look like this:
```python
cfg = get_cfg()

for cfg in [cfg]:
    # Hash the config in a reproducible way to store DBs with different
    # configs in different places, but still detect when a DB with a given
    # config has already been generated.
    cfg_code = hash_(cfg)
    produces = {
        "db": db_dir() / cfg_code / "db.npy",
        "config": db_dir() / cfg_code / "config.yaml",
    }

    @pytask.mark.task(id=cfg_code)
    @pytask.mark.produces(produces)
    def task_make_db(depends_on, produces, cfg=cfg):
        np.save(produces["db"], np.eye(2))
        save_cfg(cfg, produces["config"])
```

This works very well; new data gets generated according to the passed config and if data with this config already exists, it is not re-generated.

However, the problem is when I want to write a task that depends on `task_make_db`:
```python
pipeline_cfg = create_config_from_dict(
    {
        "new_task_config": # Config specific to the current task
        "data": # Config to be passed down to `task_make_db`
    }
)

for pipeline_cfg in [pipeline_cfg]:
    # Declare a dependency on `task_make_db`
    db_cfg = pipeline_cfg.get("data")
    db_cfg_code = hash_(db_cfg)
    depends_on = {"data": db_dir() / db_cfg_code / "db.npy"}

    # Hash the whole config to get the `produces` directories
    pipeline_cfg_code = hash_(pipeline_cfg)
    produces = {
        "output": output_dir() / pipeline_cfg_code / "output.pkl",
        "config": output_dir() / pipeline_cfg_code / "config.yaml",
    }

    @pytask.mark.task(id=pipeline_cfg_code)
    @pytask.mark.depends_on(depends_on)
    @pytask.mark.produces(produces)
    def task_make_output_from_db(depends_on, produces, cfg=pipeline_cfg):
        print(f"Doing stuff with db...")

        save_cfg(cfg, produces["config"])
```

Then when I run `task_make_output_from_db`, `pytask` tells me that `task_make_output_from_db` cannot find the required dependency, and that no tasks produces this dependency. Note that when the file does exist (because I ran `task_make_db` with the right config previously), everything works as intended.

I understand that `pytask` can't link a hash to the corresponding config; but do you see a way to get the behaviour I want, or am I stretching `pytest` to do things it was designed to do?

Let me know if you have any questions; sorry for the long-winded question. Thanks very much for your attention.

**Comment by tobiasraabe** [comment] 2022-11-25 10:07
Hi @augustebaum, just a quick answer. Maybe it already helps.

1. pytask is definitely made for these situations. Follow this how-to guide to scale multiple repeated tasks: https://pytask-dev.readthedocs.io/en/stable/how_to_guides/bp_scalable_repetitions_of_tasks.html. Maybe I should cross-reference it in the tutorial, so it is easier to discover.
2. It looks like your example could work. Why are the hashes `cfg_code` and `db_cfg_code` different? Do they really hash the same thing? I would try to debug that.

**Comment by augustebaum** [comment] 2022-11-25 10:22
Thanks for the quick answer!
1. I've read this bit of the docs, thanks for reminding me of it! I don't yet see how this applies to my problem -- I'll read it more carefully.
2. The `cfg` in the second example refers to the config for `task_make_output_from_db`. Since this task depends on `task_make_db` which requires parameters, `cfg` includes a key `"data"` mapping to a config of the form expected by `task_make_db`. `task_make_db` processes the data produced by `task_make_db` in a parametrizable way as well, so the parameters it expects are contained in the `"new_task_config"` part of `cfg`.
> ```python
> cfg = create_config_from_dict(
>     {
>         "new_task_config": # Config specific to the current task
>         "data": # Config to be passed down to `task_make_db`
>     }
> )
> ```
`db_cfg_code` refers to the data generation task only, whereas `cfg_code` refers to the data manipulation _as well as the data generation_; therefore these two hashes are **not** expected to be the same.
Does this answer your question? I find it difficult to express my problem simply; I'll be grateful for any opportunity to clarify anything, for my own sake as well as yours.

Thanks again for your attention!

**Comment by augustebaum** [comment] 2022-11-25 14:24
I re-read [the mentioned docs page](https://pytask-dev.readthedocs.io/en/stable/how_to_guides/bp_scalable_repetitions_of_tasks.html) and one thing that struck me is that, in the examples given, the `ESTIMATIONS` dict contains every possible combination of kwargs to be passed down to the tasks.
In my case, the config can get complicated, e.g. I could ask `task_make_db` to generate a dataframe with 5 rows, or 10, or 100 rows; I could also vary the number of columns, and so on. Similarly, if I were to train a model to learn patterns in the data, I might want to vary the number of parameters: for example if training a deep neural network I'd like to be able to specify the hidden layer sizes by a list like `[50, 75, 100]` (50 nodes in the first hidden layer, 75 in the second, 100 in the third).
So I can't enumerate all the possible configs to put them in a dict.

In light of this I just want to make sure so I'll ask again: is this out of scope for `pytask`?

**Comment by tobiasraabe** [comment] 2022-11-25 16:08
> db_cfg_code refers to the data generation task only, whereas cfg_code refers to the data manipulation and the data generation; therefore, these two hashes are not expected to be the same.

I was a little imprecise. `cfg_code` is used in the loop of both tasks. Shouldn't `cfg_code` inside the loop from `task_make_db` match `db_cfg_code` in the loop of `task_make_output_from_db`? Probably, they are different, so the path `db_dir() / db_cfg_code / "db.npy"` is different.

For debugging, use one iteration or present an even more reproducible example where the configs are directly derived from one another.

**Comment by tobiasraabe** [comment] 2022-11-25 16:15
> In light of this I just want to make sure so I'll ask again: is this out of scope for pytask?

I do not see why it should be out of scope for pytask. I used it in research projects with 1000s of simulations derived from similar cartesian products of input parameters. You need to specify what you are exactly concerned about.

The only thing I see is that if you want to use pytask for hyperparameter search, there might be better options somewhere provided by ML community that give you some other things out-of-the-box like intelligent parameter search with Bayesian learning, dashboards, automatic deployment to AWS, whatever.

**Comment by augustebaum** [comment] 2022-11-25 16:34
> > db_cfg_code refers to the data generation task only, whereas cfg_code refers to the data manipulation and the data generation; therefore, these two hashes are not expected to be the same.
> 
> I was a little imprecise. `cfg_code` is used in the loop of both tasks. Shouldn't `cfg_code` inside the loop from `task_make_db` match `db_cfg_code` in the loop of `task_make_output_from_db`? Probably, they are different, so the path `db_dir() / db_cfg_code / "db.npy"` is different.
> 
> For debugging, use one iteration or present an even more reproducible example where the configs are directly derived from one another.

Oops this is my fault; the two snippets would be in different files. I should have used different variable names between the two snippets.

**Comment by augustebaum** [comment] 2022-11-25 16:41
> > In light of this I just want to make sure so I'll ask again: is this out of scope for pytask?
> 
> I do not see why it should be out of scope for pytask. I used it in research projects with 1000s of simulations derived from similar cartesian products of input parameters. You need to specify what you are exactly concerned about.
> 
> The only thing I see is that if you want to use pytask for hyperparameter search, there might be better options somewhere provided by ML community that give you some other things out-of-the-box like intelligent parameter search with Bayesian learning, dashboards, automatic deployment to AWS, whatever.

Thanks! I want to stress that the point is not (yet) to explore different hyperparameters in one `pytask` run; what I want is to use a config file for a full end-to-end ML pipeline: data generation, model training, plot data computation, and plot generation, with the added bonus that, if I launch a run with the same config but just ask for a different plot, `pytask` can just re-use the intermediate data.
I haven't found any example anywhere of `pytask` being used this way, hence my wondering if there were any resources I was unaware of.
I'm going to keep working on it and see if I reach an acceptable solution.

**Closed** 2023-10-11 13:55 UTC
Labels: question
