### ISSUE TITLE
ENH: Specify cause of segmentation fault when importing certain packages.

### ISSUE THREAD

**Issue by MDanialSyed** [pytask-dev/pytask#359] opened 2023-03-17 07:59 UTC
#### Is your feature request related to a problem?

When trying to 
`import torch`
`import torchvision`

in a repository task, the task would fail with exit error "segmentation fault pytask".

#### Describe the solution you'd like

Some kind of error specification where the issue occurred as the segfault error is otherwise difficult to trace. 

#### Describe alternatives you've considered

The workaround was to add the affected libraries to the environment.yml - specify pytorch in the channel, and pytorch and torchvision in the list of packages. Or alternatively running `conda install pytorch torchvision -c pytorch` in the activated repository environment.

**Comment by tobiasraabe** [comment] 2023-03-17 12:20
Hi @MDanialSyed!

This does not seem like an error related to pytask and more an error with the PyTorch installation. For example, mixing pip and conda packages can create such problems.

It also seems super similar to this issue: `https://github.com/pytest-dev/pytest/issues/8841` where people also decided the problem is withPyTorchh and not pytest.

Given that, I would close the issue. Please follow up if you think there is still something pytask should do.

Cheers!

PS: When reporting a problem, the best way is to provide a reproducible example. You specified that you imported the libraries but not how you installed them, which is particularly interesting if installing the packages from another source fixes the issue.

**Comment by MDanialSyed** [comment] 2023-03-17 14:22
@tobiasraabe Thanks a lot for the clarifying answer and the link to a related issue. Super helpful! Maybe we can close out this issue then.

**Closed** 2023-03-17 14:23 UTC
Labels: enhancement
